steps:
  - command:
      - "pip install locust"
      - "locust -f /workdir/locustfile.py -u 5 -r 1 -t 2m -H https://gorest.co.in --headless --only-summary --csv=/workdir/results"
    env:
      GOREST_TOKEN: "## YOUR GOREST TOKEN HERE ##"
    plugins:
      - docker#v3.8.0:
          image: "python:3"
          propagate-environment: true
          mount-checkout: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    artifact_paths: "./results*.csv"
